version: '3.9'

services:
  db:
    image: postgres
    volumes:
      - ../data/db:/var/lib/postgresql/data
    env_file:
      - .env/dev
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --username=${POSTGRES_USER} --dbname=${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn -c "gunicorn.config.py" app.main:app
    image: fastapi_first
    ports:
      - "8001:8000"
    env_file: .env/dev
    environment:
      - SETTINGS_MODULE=development
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5433
    depends_on:
      db:
        condition: service_healthy
    restart: always

