version: '3.9'

services:
  postgresql:
    image: postgres
    volumes:
      - ../data/db:/var/lib/postgresql/data
    env_file: ../.env
    ports:
      - "5433:5432"
    restart: always
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    image: fastapi_first
    ports:
      - "8001:8000"
    env_file: ../.env
    links:
      - postgresql
    restart: always

