"""create group

Revision ID: 8debf8f31282
Revises: 4a11d821ca00
Create Date: 2022-08-01 10:54:58.614644

"""
from alembic import op
import sqlalchemy as sa

import sqlmodel

# revision identifiers, used by Alembic.
revision = '8debf8f31282'
down_revision = '4a11d821ca00'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group',
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_group_id'), 'group', ['id'], unique=False)
    op.create_table('groupuserlink',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'group_id')
    )
    op.add_column('permission', sa.Column('group_id', sa.Integer(), nullable=False))
    op.drop_constraint('permission_user_id_fkey', 'permission', type_='foreignkey')
    op.create_foreign_key(None, 'permission', 'user', ['group_id'], ['id'])
    op.drop_column('permission', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permission', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'permission', type_='foreignkey')
    op.create_foreign_key('permission_user_id_fkey', 'permission', 'user', ['user_id'], ['id'])
    op.drop_column('permission', 'group_id')
    op.drop_table('groupuserlink')
    op.drop_index(op.f('ix_group_id'), table_name='group')
    op.drop_table('group')
    # ### end Alembic commands ###
