name: Run tests on pull request to dev or master branches
on:
  pull_request:
    branches:
      - 'dev'
      - 'master'

jobs:
  run_tests:
    runs-on: ubuntu-latest
    environment: testing_env
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      PG_DSN: ${{ secrets.PG_DSN }}
      ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS }}
      ORIGINS: ${{ secrets.ORIGINS }}
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: ${{ secrets.POSTGRES_NAME }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install requirements
        run: pip install -r requirements/requirements.txt
      - name: Run tests
        run: pytest
      - name: Download test logs
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: test-results
          path: logs