name: Run tests on any Push event
on:
  push:
    branches:
      - '*'


jobs:
  run_tests:
    runs-on: ubuntu-latest
    environment: TEST
    container: python:3.10
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@master
      - name: Install requirements
        run: pip install -r requirements/requirements.txt
      - name: Run tests
        run: pytest