name: Run tests on any Push event
on:
  push:
    branches:
      - '*'


jobs:
  run_tests:
    runs-on: ubuntu-latest
    environment: TEST
    container: python:3.10
    env:
      POSTGRES_DB: ${{ secrets.POSTGRES_NAME }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      PG_DSN: ${{ secrets.PG_DSN }}
      ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS }}
      ORIGINS: ${{ secrets.ORIGINS }}
    services:
      postgres:
        image: postgres

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@master
      - name: Install requirements
        run: pip install -r requirements/requirements.txt
      - run: |
          echo 'printing envs'
          env
      - name: Run tests
        run: pytest