name: Run tests on any Push event
on:
  push:
    branches:
      - '*'

env:
  TEST_ENV_FILE: ${{ secrets.TEST }}
  POSTGRES_DB: ${{ secrets.TEST.POSTGRES_NAME }}
  POSTGRES_USER: ${{ secrets.TEST.POSTGRES_USER }}
  POSTGRES_PASSWORD: ${{ secrets.TEST.POSTGRES_PASSWORD }}

jobs:
  run_tests:
    runs-on: ubuntu-latest
    container: python:3.10
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@master
      - name: Install requirements
        run: pip install -r requirements/requirements.txt
      - name: Unpack envs
        run: mkdir .env && echo $QA_ENV_FILE | base64 --decode > .env/test
      - name: Run tests
        run: pytest